
server:
  port: 8080
  servlet.context-path: /customer
#
#spring.datasource.url=jdbc:postgresql://192.168.5.54:5432/customer
#spring.datasource.
spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://192.168.5.54:5432/customer
    password: 123@123aA
    driver-class-name: org.postgresql.Driver
    username: postgres
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true

  cloud:
    compatibility-verifier:
      enabled: false
redis:
  mode: single
  config-file: E:\\HuyVAProject\\microservice\\config\\redisson.yaml
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.5.59:8761/eureka}
  instance:
    preferIpAddress: true
jwt:
  secret: vuanhhuy12312234
  time-out: 100000000
